### ISSUE TITLE
Unable to access Mersenneforum (connection timeout)

### ISSUE THREAD

**Issue by Stargate38** [bbuhrow/yafu#14]
This may not be directly YAFU-related, but I can't access Mersenneforum, no matter how many times I reload it. It keeps giving me timeout errors. I was able to access it earlier today. If you're having problems with it, please tell me what's wrong, or how to contact Xyzzy to get it fixed.

**Comment by kotenok2000** [comment]
Works for me now.

**Comment by bbuhrow** [comment]
This isn't really the place for that kind of report... but yes it was down and now is working again.
