### ISSUE TITLE
FACT0RN mining Yafu leaks memory

### ISSUE THREAD

**Issue by ReverseControl** [bbuhrow/yafu#17]
Hi,

The[ FACT0RN blockchain](https://github.com/FACT0RN/FACT0RN) uses YAFU to [mine](https://github.com/FACT0RN/factoring) its coin by factoring. Several miners have reported an issue whereby when they have miners running for over a day the miners will reach a point where it will use all the memory in the system, 16GB in some systems and 64GB in others. Granted, these systems have multiple miners running at once, but there should be enough resources for all of them as it runs well for about a day. 

Miners will factor tens of thousands of numbers a day of about 280-bits right now --- that is the blockchain difficulty level now. The algorithm we are using right now is SIQS. Could you please look into this?

I've looked at our python miner code and I cannot find a memory leak even after profiling the memory of the python code at runtime.

~Escanor

**Comment by bbuhrow** [comment]
Please tell me exactly how yafu is called.  Is it given a batchfile?  a
pipe?  called with some syscmd repeatedly?  something else?

**Comment by ReverseControl** [comment]
@bbuhrow  The line in the code is this: https://github.com/FACT0RN/factoring/blob/main/python/number_theory.py#L91.

The code is:

```
  proc = subprocess.Popen([YAFU_BIN,"-one","-threads",YAFU_THREADS,"-lathreads",YAFU_LATHREADS, str(n)],stdout=subprocess.PIPE)

```

**Comment by ReverseControl** [comment]
@bbuhrow Any updates?

**Comment by bbuhrow** [comment]
I fixed several memory leaks using valgrind.  If you are building from source you will have to also re-build ytools/ysieve, since some of the memory leaks were in ysieve.
