### ISSUE TITLE
running on xeon phi coprocessor

### ISSUE THREAD

**Issue by daedalus** [bbuhrow/yafu#23]
Hi, 

I understand that compiling yafu with the ICX compiler is enough to run it inside the xeon phi coprocessor.

Is that ok?

**Comment by bbuhrow** [comment]
ICX should know how to compile for a xeon phi coprocessor, yes, but I have never done it so I can't guarantee it will work.  Also the code for KNC xeon phi is really old; hasn't been tested in ages.  If it is a KNL you are targetting then there is a better chance it will work.

**Comment by daedalus** [comment]
Thanks
