### ISSUE TITLE
get error matrix needs more columns than rows; try adding 2-3% more relations

### ISSUE THREAD

**Issue by RichardAth** [bbuhrow/yafu#26]
I have an old PC that doesn't support AVX512, so I had to rebuild YAFU from the source, changing options to get an executable program. I found that using default yafu.ini options, when factoring 2^277 - 1 I get the error " matrix needs more columns than rows; try adding 2-3% more relations" in the log file after seeing the message "nfs: commencing msieve linear algebra". 

Adding "snfs_xover=79" to the yafu.ini file seems to be an effective workaround.

In order to get some diagnostics, I have replaced exit(-1) with abort() in a number of places, as this creates the option to enter the debugger instead of just terminating.

**Comment by bbuhrow** [comment]
The default snfs crossover has been raised to 95 digits, which should help here.  Thank you
