### ISSUE TITLE
Yafu refuses to work with git version of cado-nfs

### ISSUE THREAD

**Issue by kotenok2000** [bbuhrow/yafu#32]
Tested on https://gitlab.inria.fr/cado-nfs/cado-nfs/-/commit/1562532124feb19fb391736069c4d66eef52ecba

```
./yafu  -noecm "factor(584486107317716929200065348863299793437114484660635316865207341662351147505738426439485540680846329373181208257824336915629)" 


fac: using pretesting plan: noecm
Info:root: No database exists yet
Traceback (most recent call last):
  File "/home/user/git/cado-nfs/cado-nfs.py", line 144, in <module>
    parameters, db = toplevel_params.get_cooked_parameters()
  File "/home/user/git/cado-nfs/scripts/cadofactor/toplevel.py", line 1180, in get_cooked_parameters
    self.access_or_create_workdir_and_db()
  File "/home/user/git/cado-nfs/scripts/cadofactor/toplevel.py", line 680, in access_or_create_workdir_and_db
    raise ValueError("Given working directory must be an absolute path: %s" % a)
ValueError: Given working directory must be an absolute path: cadoWorkdir
```

**Comment by kotenok2000** [comment]
Commit https://gitlab.inria.fr/cado-nfs/cado-nfs/-/commit/f084a550a9fc7a9f6879b32b3e83c1b8b8b5adc1 works

**Comment by bbuhrow** [comment]
Cado-nfs functionality was added by a collaborator, I am unable to support it at this time.

**Comment by kotenok2000** [comment]
Notified nyancat at https://www.mersenneforum.org/showthread.php?t=28030&page=2

**Comment by bbuhrow** [comment]
Thank you, hopefully he is still willing and able to help.

**Comment by NyanCatTW1** [comment]
Reverting commit https://gitlab.inria.fr/cado-nfs/cado-nfs/-/commit/9ae43f7eace21b802ffec3fae39f0594d9b7f008 works too
I'll find some time within this week to fix it properly, along with publishing some fix and optimization that I made on local

**Comment by kotenok2000** [comment]
Will you merge it?

**Comment by kotenok2000** [comment]
NyanCatTW1
I have got another bug for you 
https://github.com/bbuhrow/yafu/issues/42
