### ISSUE TITLE
Why couldn't you embed ytools and ysieve as git submodules?

### ISSUE THREAD

**Issue by kotenok2000** [bbuhrow/yafu#34]

**Comment by bbuhrow** [comment]
I don't know how to do this yet.  I know that yafu can be difficult to build but that fact is unlikely to change anytime soon without help.

**Comment by tdulcet** [comment]
Running these two commands from the root directory of the repository should do the trick:
```sh
git submodule add https://github.com/bbuhrow/ytools.git
git submodule add https://github.com/bbuhrow/ysieve.git
```
