### ISSUE TITLE
Occasional invalid time reported in the factor.json file

### ISSUE THREAD

**Issue by RichardAth** [bbuhrow/yafu#36]
This problem occurs randomly. It does not seem to be consistently reproducible, but has happened more than once. A json record that showed the problem is:

{ 	"input-expression":"factor(6427752177035961102167848373630136223531775382492390539399167)", 	"input-decimal":"6427752177035961102167848373630136223531775382492390539399167", 	"input-argument-string":"factor(6427752177035961102167848373630136223531775382492390539399167) -p -v ", 	"factors-prime":["158456325028528675187087900777","40564819207303340847894502572071"], 	"pm1-curves" : {"150000":1}, 	"ecm-curves" : {"2000":30,"11000":55}, 	"ecm-levels" : {"t15":5.58,"t20":0.78,"t25":0.04}, "ecm-sum":18.89, 	"runtime" : {"total":4.5757, "ecm":1.0673, "pm1":0.0700, "pp1":1144905460970637740319230447308250197200330079117347756920918180400020346932410620435634833219406731944686642943660623986101615924980860077182985110151764034212223807485378266354231739678665761374948502214015544719429364243621736532418941157376.0000, "siqs":2.4335}, 	"time-start" : "2024-02-12  16:58:18", 	"time-end" : "2024-02-12  16:58:23", 	"info":{"compiler":"MSVC 1935","ECM-version":"7.0.4","MPIR-version":"3.0.0","yafu-version":"2.11"} }

The problem is that the pp1 time is reported as more than 10^243 seconds. I noticed this because the json parser I used had a bug (now fixed) and flagged this number as having an invalid format.

Added 19 Feb 24:
After some thought I decided that the problem was that the time printed is random meaningless data. Also it appears that as the data area used is allocated using malloc, and ttime is never explicitly set to zero, the random 'time' could be there from initialisation. I added the following line to function init_factobj in file factor_common.c:

    fobj->pp1_obj.ttime = NAN;    /* set to NAN added 16/2/24 */

and, sure enough, when writing the JSON object, ttime still had the value NAN.

**Comment by bbuhrow** [comment]
Should be fixed now in version 2.12
