### ISSUE TITLE
B1 passed to GMP-ECM is not settable through interactive session.

### ISSUE THREAD

**Issue by alexhiggins732** [bbuhrow/yafu#4]
**Background**: I am currently building Yafu wrappers with the goal of creating packages for consumption by higher level languages such as Python and C# via package managers such as a PIP and Nuget to expose Yafu for public consumption from a broader audience. The current structure of Yafu isn't amenable to simply creating a c library which can be called directly through higher level bindings so I am instead attempting to invoke Yafu as a standard process and and send commands to it in the wrapper and parse the standard output. This itself has some issues due to how Yafu handles pipes and redirections but I have implemented some workarounds despite the code smells involved.

**Issue**: B1 passed to GMP-ECM is not settable through interactive session. I know the documentation states B1ecm and B2ecm are command line flags. I was hoping to be able to set them through the interactive session and run the specified number of curves. which would result in an output like this:

``` 
>> B1ecm

ans = 0

>> B1ecm = 1500000

B1ecm = 1500000

>>ecm(rsa(200), 500)

ecm: 1/500 curves on C30, B1=1500k, B2=gmp-ecm default, ETA: 6.8 min

***factors found***

P16 = 4509593602124327

***co-factor***
P15 = 179453758677551

ans = 179453758677551
```

The command line equivalent is:

```
yafu -B1ecm 1500000 ecm(rsa(100),500)
```

Instead, setting `B1ecm = 1500000` has no effect and the default B1 is used:

```
ecm: 500/500 curves on C60, B1=11k, B2=gmp-ecm default
```

Under the hood the wrappers *could* create a new Yafu process with distinct command line parameters but I was hoping avoid the overhead of create a new process (and the underlying initialization Yafu performs) by creating allow the wrappers to just use standard i/o redirection.

Thank you for your consideration and thank you for this excellent library.

**Comment by bbuhrow** [comment]
Hi Alex thanks for your interest!  I am actually working on restructuring things so that reusable libraries can be built, but it's not ready yet.  Or, I can try to help enable your plan.  Either way, please be patient as this is hobby spare time stuff and also I am still learning how to make things more reusable.  The focus so far with this project has been mostly performance,  not reuseability.

**Comment by kotenok2000** [comment]
Now, when version 2 is released will you return to this issue?

**Comment by bbuhrow** [comment]
Options variables can now be set during an interactive session.  The verbosity option 'v' is set using the variable name 'verbose'.  All others use their option names (e.g., to change ECM B1, use B1ecm=1000000).
